### ISSUE TITLE
Question about not running on mobile

### ISSUE THREAD

**Issue by darrinmn9** [SamKnows/vue-futurelink#2]
I realize in the code you don't run the mounting logic if your on mobile. Is this because you don't want to preload links and potentially waste bandwidth on mobile? Or is there actually a piece of this code that won't work correctly on mobile devices?

**Comment by callumacrae** [comment]
it's because you can't predict where the cursor is being moved to on mobile, because there is no cursor

**Comment by darrinmn9** [comment]
Ah duh... thank you. 

By the way, do you happen to have another link for the writeup on this? The original medium link was broken, but I was trying to learn more on this subject. I was also a little confused on the tradeoffs of this library for "preloading" links, vs something like https://github.com/egoist/vue-router-prefetch that "prefetches" links.

**Comment by callumacrae** [comment]
It's moved to here: https://samknows.com/blog/intelligent-page-preloading-with-futurelink

I haven't seen that library before - does it load all the links on the page? That seems wasteful!
